<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Trax (trax.Trax)</title><link rel="stylesheet" href="../../_odoc-theme/odoc.css"/><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><script src="../../highlight.pack.js"></script><script>hljs.initHighlightingOnLoad();</script></head><body><div class="content"><header><nav><a href="../index.html">Up</a> â€“ <a href="../index.html">trax</a> &#x00BB; Trax</nav><h1>Module <code>Trax</code></h1></header><dl><dt class="spec type" id="type-location"><a href="#type-location" class="anchor"></a><code><span class="keyword">type</span> location</code><code> = </code><table class="variant"><tr id="type-location.Text" class="anchored"><td class="def constructor"><a href="#type-location.Text" class="anchor"></a><code>| </code><code><span class="constructor">Text</span> <span class="keyword">of</span> string</code></td></tr><tr id="type-location.Raw_backtrace" class="anchored"><td class="def constructor"><a href="#type-location.Raw_backtrace" class="anchor"></a><code>| </code><code><span class="constructor">Raw_backtrace</span> <span class="keyword">of</span> <a href="../../ocaml/Stdlib/Printexc/index.html#type-raw_backtrace">Stdlib.Printexc.raw_backtrace</a></code></td><td class="doc"><p>The type of locations that make up the exception trace</p></td></tr></table></dt></dl><dl><dt class="spec exception" id="exception-Traced"><a href="#exception-Traced" class="anchor"></a><code><span class="keyword">exception</span> </code><code><span class="exception">Traced</span> <span class="keyword">of</span> exn * <a href="index.html#type-location">location</a> list</code></dt><dd><p>Any exception and its trace</p></dd></dl><dl><dt class="spec value" id="val-wrap"><a href="#val-wrap" class="anchor"></a><code><span class="keyword">val</span> wrap : <a href="index.html#type-location">location</a> <span>&#45;&gt;</span> exn <span>&#45;&gt;</span> exn</code></dt><dd><p>Add location to this exception's trace. If the input exception is not already wrapped, it gets wrapped into a <code>Traced</code> exception. If the original exception is already wrapped in a <code>Traced</code> exception, it gets unwrapped and rewrapped with the new, extended trace.</p></dd></dl><dl><dt class="spec value" id="val-unwrap"><a href="#val-unwrap" class="anchor"></a><code><span class="keyword">val</span> unwrap : exn <span>&#45;&gt;</span> exn</code></dt><dd><p>Recover the original exception, for inspection purposes. For instance <code>Traced(Not_found, [...])</code> would become <code>Not_found</code>.</p></dd></dl><dl><dt class="spec value" id="val-wrap_with_stack_trace"><a href="#val-wrap_with_stack_trace" class="anchor"></a><code><span class="keyword">val</span> wrap_with_stack_trace : exn <span>&#45;&gt;</span> exn</code></dt><dd><p>Wrap an exception with the current exception backtrace (stack trace recorded at the point where the exception was raised, assuming no other exception was raised in-between). This is only guaranteed to work right after catching an exception with a try-with.</p></dd></dl><dl><dt class="spec value" id="val-raise_at"><a href="#val-raise_at" class="anchor"></a><code><span class="keyword">val</span> raise_at : <a href="index.html#type-location">location</a> <span>&#45;&gt;</span> exn <span>&#45;&gt;</span> <span class="type-var">'a</span></code></dt><dd><p>Raise or reraise an exception after adding a location to its trace.</p></dd></dl><dl><dt class="spec value" id="val-raise"><a href="#val-raise" class="anchor"></a><code><span class="keyword">val</span> raise : string <span>&#45;&gt;</span> exn <span>&#45;&gt;</span> <span class="type-var">'a</span></code></dt><dd><p>Raise or reraise an exception after adding a text location to its trace. Typical usage is <code>Trax.raise __LOC__ e</code>.</p></dd></dl><dl><dt class="spec value" id="val-reraise_with_stack_trace"><a href="#val-reraise_with_stack_trace" class="anchor"></a><code><span class="keyword">val</span> reraise_with_stack_trace : exn <span>&#45;&gt;</span> <span class="type-var">'a</span></code></dt><dd><p>Re-raise an exception after wrapping it with the current exception backtrace (stack trace recorded at the point where the exception was raised, assuming no other exception was raised in-between). This is only guaranteed to work right after catching an exception with a try-with.</p></dd></dl><dl><dt class="spec value" id="val-to_string"><a href="#val-to_string" class="anchor"></a><code><span class="keyword">val</span> to_string : exn <span>&#45;&gt;</span> string</code></dt><dd><p>Format the exception and its trace into text.</p></dd></dl><dl><dt class="spec value" id="val-get_trace"><a href="#val-get_trace" class="anchor"></a><code><span class="keyword">val</span> get_trace : exn <span>&#45;&gt;</span> string</code></dt><dd><p>Format the trace into text</p></dd></dl><dl><dt class="spec value" id="val-print"><a href="#val-print" class="anchor"></a><code><span class="keyword">val</span> print : <a href="../../ocaml/Stdlib/index.html#type-out_channel">Stdlib.out_channel</a> <span>&#45;&gt;</span> exn <span>&#45;&gt;</span> unit</code></dt><dd><p>Print the exception and its trace.</p></dd></dl></div></body></html>